name: Browser Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/explorama/images/build-image:latest
    defaults:
      run:
        working-directory: ./bundles/browser
    steps:
      - uses: actions/checkout@v6
      - run: apk add --no-cache tar
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: "m2-browser-${{ hashFiles('bundles/browser/deps.edn') }}-${{ hashFiles('bundles/browser/package-lock.json') }}"
      - name: Prepare test
        run: |
          npm install
          mv figwheel-headless-ci.sh.template figwheel-headless.sh
      - name: Run tests
        run: |
          npm run test-ci
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: "**/*report.xml"
