name: Browser Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/explorama/images/build-image:latest
    defaults:
      run:
        working-directory: ./bundles/browser
    steps:
      - uses: actions/checkout@v6
      - run: apk add --no-cache tar
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: "m2-browser-${{ hashFiles('bundles/browser/deps.edn') }}-${{ hashFiles('bundles/browser/package-lock.json') }}"
      - name: Prepare test
        run: |
          npm install
          mv figwheel-headless-ci.sh.template figwheel-headless.sh
      - name: Run tests
        run: |
          npm run test-ci
      - name: Write to Job Summary
        run: cat report.xml >> $GITHUB_STEP_SUMMARY
